name: pocketgm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  chessground: ^7.2.0
  dartchess: ^0.11.1
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.0
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  http: ^1.6.0
  shared_preferences: ^2.5.3
  stockfish: ^1.7.1
  uuid: ^4.5.1
  vibration: ^3.1.4
  volume_controller: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
